[toc]

# 03_02_예외처리

## 에러(Error)

### 문법 에러(`SyntaxError`)

> 문법 에러가 있는 프로그램은 실행되지 않는다!!

- 에러 발생 시 `SyntaxError`라는 키워드와 함께, 에러의 상세 내용을 보여줍니다.

- `파일이름`과 `줄번호`, `^` 문자를 통해 파이썬이 코드를 읽어 들일 때(`parser`) 문제가 발생한 위치를 표현합니다.

- `parser` 는 줄에서 에러가 감지된 가장 앞의 위치를 가리키는 캐럿(caret)기호(`^`)를 표시합니다.



### 예외(Exception)

> 실행 도중 예상하지 못한 상황(exception)을 맞이하면, 프로그램 실행을 멈춥니다.

- 문법적으로는 옳지만, 실행 시 발생하는 에러

- *아래 제시된 모든 에러는 `Exception`을 상속받아 이뤄집니다.*



#### `ZeroDivisionError`

파이썬에서는 어떤 수를 0으로 나누게 되면 발생하는 에러



#### `NameError`

지역 혹은 전역 이름 공간 내에서 유효하지 않는 이름은 사용할 수 없다.
즉, 어느 곳에서도 정의되지 않은 변수를 호출하였을 경우 발생하는 에러



#### `TypeError`

* 자료형이 올바르지 못한 경우 

> ```
> TypeError: unsupported operand type(s) for +: 'int' and 'str'
> TypeError: type str doesn't define __round__ method
> ```

* 함수 호출 과정에서 필수 매개변수가 누락된 경우

> ```
> TypeError: sample() missing 1 required positional argument: 'k'
> ```

- 함수 호출 과정에서 매개변수 개수가 초과해서 들어온 경우

> ```
> TypeError: choice() takes 2 positional arguments but 3 were given
> ```



#### `ValueError`

* 자료형은 올바르나 값이 적절하지 않은 경우

> ```
> ValueError: invalid literal for int() with base 10: '3.5'
> ```

* 존재하지 않는 값을 찾고자 할 경우

> ```
> ValueError: 3 is not in list
> ```



#### `IndexError`

* 존재하지 않는 index로 조회할 경우

> ```
> IndexError: list index out of range
> ```



#### `KeyError`

* 존재하지 않는 Key로 접근한 경우

> ```
> KeyError: 'queen' # 딕셔너리에 존재하지 않는 key를 말해줌
> ```



#### `ModuleNotFoundError`

- 존재하지 않는 Module을 `import` 하는 경우

> ```
> ModuleNotFoundError: No module named 'say'
> ```



#### `ImportError`

- Module은 찾았으나 존재하지 않는 클래스/함수를 가져오는 경우

> ```
> ImportError: cannot import name 'sampl' from 'random' (C:\Users\bljh1\AppData\Local\Programs\Python\Python39\lib\random.py)
> ```



#### `KeyboardInterrupt`

- 사용자가 임의로 실행을 중단한 경우
- 주피터 노트북에서는 정지 버튼이지만, 실제로 우리가 돌릴 때는 `ctrl`+`c`를 통해 종료하였을 때 발생합니다.



#### `IndentationError`

- Indentation(들여 쓰기)이 적절하지 않은 경우

> ```
> IndentationError: expected an indented block
> IndentationError: unexpected indent
> ```



## 예외 처리(Exception Handling)

### `try` & `except`

`try`문과 `except`절을 사용하여 예외 처리를 할 수 있다.

* 기초 문법

```python
try:
    <코드 블록 1>
except (예외):
    <코드 블록 2>
```

- `try` 아래의 코드 블록(code block)이 실행됩니다.
- 예외가 발생되지 않으면, **`except` 없이 실행이 종료됩니다.**
- 예외가 발생하면, **남은 부분을 수행하지 않고**, `except`가 실행됩니다.



```python
num = input('정수를 입력하세요: ')

try:
    print(int(num))
except ValueError:
    print('숫자를 입력하세요!')
    
# 정수를 입력하세요: 나우리날
# 숫자를 입력하세요!
```



* **복수의 예외 처리**

하나 이상의 예외를 모두 처리할 수 있다. 괄호가 있는 튜플로 여러 개의 예외를 지정할 수 있다. 

* 활용법

```python
try:
    <코드 블록 1>
except (예외 1, 예외 2):
    <코드 블록 2>

try:
    <코드 블록 1>
except 예외 1:
    <코드 블록 2>
except 예외 2:
    <코드 블록 3>
```

>  중요!!! 에러가 순차적으로 수행되기 때문에, 가장 작은 범주부터 시작해야 한다.

```python
try:
    num = input('값을 입력하시오: ')
    print(100/int(num))
except ValueError:
    print('정수를 넣어')
except Exception: # Exception 은 가장 큰 범주
    print('모르겠지만 에러야')

# 값을 입력하시오: 3.5
# 정수를 넣어
```



### `else` 활용

- 에러가 발생하지 않는 경우 수행되는 문장은 `else`를 이용합니다.
- 모든 `except` 절 뒤에 와야 합니다.
- `try` 절이 예외를 일으키지 않을 때 실행되어야만 하는 코드에 적절합니다.

```python
idx = int(input('0 이상의 수 입력: '))
try:
    numbers = [1, 2, 3]
    number = numbers[idx]
except IndexError:
    print('오류발생')
else: 
    print(number * 100)
    
# 123 입력 => 오류발생
# 2 입력 => 300
```



### `finally` 활용

- 반드시 수행해야 하는 문장은 `finally`를 활용합니다.
- 즉, 모든 상황에 실행되어야만 하는 코드를 정의하는데 활용합니다.
- 예외의 발생 여부와 관계없이 `try` 문을 떠날 때 항상 실행합니다.

```python
try:
    print('성적 파일을 읽어옵니다.')
    data = {'python': 'A+'}
    data['java']
except KeyError as err:  # keyerror가 나는 대상을 err에 담았다. 즉 'java'가 err에 담겨진다
    print(f'{err}는 딕셔너리에 없는 키입니다.')
finally:
    print('종료')

# 성적 파일을 읽어옵니다.
# 'java'는 딕셔너리에 없는 키입니다.
# 종료
```



### 에러 메시지 처리 `as`

`as` 키워드를 활용하여 에러 메시지를 보여줄 수도 있다.

* 활용법

```python
try:
    <코드 블럭 1>
except 예외 as err:
    <코드 블럭 2>
```

* 예시

```python
try:
    empty_list = []
    print(empty_list[-1])
except IndexError as msg:
    print(f'ERROR: {msg}가 범위 밖에 있습니다')
    
# ERROR: list index out of range가 범위 밖에 있습니다
```



### 예외 발생 시키기(Exception Raising)

#### `raise`

`raise`를 통해 예외를 강제로 발생시킬 수 있습니다.

* 활용법

```python
raise <에러>('메시지')
```

* 예시

```python
def avg(scores):
    try:
        return sum(scores) / len(scores)
    except ZeroDivisionError:
        raise ValueError(f'인자의 길이가 0입니다. 길이가 0이 아닌 인자를 입력하세요')
    except TypeError:
        raise TypeError (f'인자는 list tuple range set의 자료형이어야 하며, 정수로 입력하세요')

avg([])         # => ValueError: 인자의 길이가 0입니다. 길이가 0이 아닌 인자를 입력하세요
avg([1,2,3])  	# => 2
avg(100) 		# => TypeError: 인자는 list tuple range set의 자료형이어야 하며, 정수로 입력하세요
```



#### `assert`

`assert` 문은 예외를 발생시키는 다른 방법입니다.

보통 **상태를 검증하는데 사용**되며 무조건 `AssertionError`가 발생합니다.